### ISSUE TITLE
Structs used as parameters are serialized differently in test and prod code

### ISSUE THREAD

**Issue by guyroyse** [DarthStrom/MockingBird#18]
Having some problems with passing structs into Moxie. The call to [].describe being used to create a key for the stubbings renders differently in test code vs. app code. The test code is including the module name for the struct. The app code is not since that is where the struct is defined. This results in stubbings returning nil instead of what was stubbed.

I can certainly think of a few workarounds for this. For example, I could only use primitives. Or, I could put my test and prod code in the same modules. But these are not terribly attractive options.

**Comment by DarthStrom** [comment]
Yeah, there's probably a better way to generate keys.  I'll look into it.  Thanks.

**Comment by guyroyse** [comment]
If it were Java, I would suggest a hash.

**Comment by DarthStrom** [comment]
I am not able to write a failing test for this - do you have an example?

**Comment by guyroyse** [comment]
I will try to pull down the repo and create a failing test. I was, admittedly, lazy and didn't do that. My project structure is probably more complex than what is in place for this repo. It might be a bit challenging.

**Comment by DarthStrom** [comment]
That would be helpful. Here's what I tried...

In the production module I had:

```swift
class Poso {
    var valueGetter: ValueGetter = SimpleValueGetter()

    func getValue(fromStruct s: PlainStruct) -> Int {
        return valueGetter.getValue(s)
    }
}

protocol ValueGetter {
    func getValue(_ s: PlainStruct) -> Int
}

struct SimpleValueGetter: ValueGetter {
    func getValue(_ s: PlainStruct) -> Int {
        return s.value
    }
}

struct PlainStruct {
    let name: String
    let value: Int
}
```

and in the test:

```swift
class PosoTests: XCTestCase {

    var subject: Poso!
    var mockValueGetter: MockValueGetter!

    override func setUp() {
        subject = Poso()
        mockValueGetter = MockValueGetter()
        subject.valueGetter = mockValueGetter
    }
    
    func testStructParamStubbing() {
        let plainStruct = PlainStruct(name: "1", value: 1)
        mockValueGetter.stub(function: "getValue", whenCalledWith: [plainStruct], return: 5)

        let value = subject.getValue(fromStruct: plainStruct)

        print(mockValueGetter.interactions(withFunction: "getValue"))
        XCTAssertEqual(5, value)
    }
    
}

class MockValueGetter: Mock, ValueGetter {
    var moxie = Moxie()

    func getValue(_ s: PlainStruct) -> Int {
        record(function: "getValue", wasCalledWith: [s])

        return value(forFunction: "getValue", whenCalledWith: [s]) ?? 99
    }
}

```

**Comment by DarthStrom** [comment]
So I still have not been able to reproduce this issue for structs, but there is a similar issue for classes that I'll need to figure out.  When the .description is used for classes, it is just the name of the class without any identifiable information.

**Comment by DarthStrom** [comment]
I think due to the nature of swift, I may have to abandon the idea of being able to stub for specific parameters in favor of just stubbing the method and being able to capture parameters somehow.

**Comment by guyroyse** [comment]
The repo I was having the problem with is [here](https://github.com/Nexosis/nexosisclient-swift). I removed the mocks but it would be easy to add them as Moxie is still there. For the time being, I have created my own hacky mocks.

**Comment by DarthStrom** [comment]
I made some changes to get around the limitations with differentiating based on parameters.  The changes should make this issue obsolete with the 0.2.0 release.  Coming Soon(TM)
